### ISSUE TITLE
NoMethodError: undefined method `new_session_path' for #<Users::OmniauthCallbacksController:0x000000041764d0>

### ISSUE THREAD

**Issue by JuddL333** [LasVegasRubyGroup/soapbox#12]
Check full details on Airbrake: https://lvrugtopicsapp.airbrake.io/groups/61389232?auth_token=0912968cd73fb8d8c8377e1126e5c2c2830b8615

```
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/devise-2.2.3/app/controllers/devise/omniauth_callbacks_controller.rb:28:in `after_omniauth_failure_path_for'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/devise-2.2.3/app/controllers/devise/omniauth_callbacks_controller.rb:10:in `failure'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/abstract_controller/base.rb:167:in `process_action'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_controller/metal/rendering.rb:10:in `process_action'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:447:in `_run__740375034822070564__process_action__199069502635018519__callbacks'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:405:in `__run_callback'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
[PROJECT_ROOT]/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:81:in `run_callbacks'
```

**Comment by brianvh** [comment]
Meetup's OAuth support appears to be completely broken. Please send help!

**Comment by russ** [comment]
Sent meetup support a tweet https://twitter.com/LVRUG/status/350281081477545986

**Comment by JuddL333** [comment]
Discussion with meetup can be found here: https://groups.google.com/forum/?fromgroups#!topic/meetup-api/Ox1NG2mplkU

**Comment by russ** [comment]
I've made a change to the omniauth-meetup gem. Here is the pull request:
https://github.com/tapster/omniauth-meetup/pull/4
